var businessSearchCriteria: any = {
  Type: "Agent",
  BusinessStatusID: "1",
  AgentName: "",
  PrincipalName: "",
  StartDateOfIncorporation: "",
  EndDateOfIncorporation: "",
  ExpirationDate: "",
  IsSearch: "true",
  IsShowAdvanceSearch: "true",
  "": [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  "AgentAddress[IsAddressSame]": "false",
  "AgentAddress[IsValidAddress]": "false",
  "AgentAddress[isUserNonCommercialRegisteredAgent]": "false",
  "AgentAddress[IsInvalidState]": "false",
  "AgentAddress[baseEntity][FilerID]": "0",
  "AgentAddress[baseEntity][UserID]": "0",
  "AgentAddress[baseEntity][CreatedBy]": "0",
  "AgentAddress[baseEntity][ModifiedBy]": "0",
  "AgentAddress[FullAddress]": ", WA, USA",
  "AgentAddress[ID]": "0",
  "AgentAddress[State]": "WA",
  "AgentAddress[Country]": "USA",
  "PrincipalAddress[IsAddressSame]": "false",
  "PrincipalAddress[IsValidAddress]": "false",
  "PrincipalAddress[isUserNonCommercialRegisteredAgent]": "false",
  "PrincipalAddress[IsInvalidState]": "false",
  "PrincipalAddress[baseEntity][FilerID]": "0",
  "PrincipalAddress[baseEntity][UserID]": "0",
  "PrincipalAddress[baseEntity][CreatedBy]": "0",
  "PrincipalAddress[baseEntity][ModifiedBy]": "0",
  "PrincipalAddress[FullAddress]": ", WA, USA",
  "PrincipalAddress[ID]": "0",
  "PrincipalAddress[State]": "",
  "PrincipalAddress[Country]": "USA",
};

export default businessSearchCriteria;
